/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    programs: Program;
    'news-events': NewsEvent;
    team: Team;
    'featured-volunteers': FeaturedVolunteer;
    stories: Story;
    gallery: Gallery;
    'impact-metrics': ImpactMetric;
    'homepage-testimonials': HomepageTestimonial;
    'volunteer-stats': VolunteerStat;
    'contact-inquiries': ContactInquiry;
    publications: Publication;
    partners: Partner;
    'research-tools': ResearchTool;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'news-events': NewsEventsSelect<false> | NewsEventsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'featured-volunteers': FeaturedVolunteersSelect<false> | FeaturedVolunteersSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'impact-metrics': ImpactMetricsSelect<false> | ImpactMetricsSelect<true>;
    'homepage-testimonials': HomepageTestimonialsSelect<false> | HomepageTestimonialsSelect<true>;
    'volunteer-stats': VolunteerStatsSelect<false> | VolunteerStatsSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'research-tools': ResearchToolsSelect<false> | ResearchToolsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'programs-page': ProgramsPage;
    'program-detail-page': ProgramDetailPage;
    'initiative-detail-page': InitiativeDetailPage;
    'projects-page': ProjectsPage;
    'publications-page': PublicationsPage;
    'news-page': NewsPage;
    'stories-page': StoriesPage;
    'story-detail-page': StoryDetailPage;
    'gallery-page': GalleryPage;
    'impact-page': ImpactPage;
    'research-page': ResearchPage;
    'contact-page': ContactPage;
    'news-event-detail-page': NewsEventDetailPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'programs-page': ProgramsPageSelect<false> | ProgramsPageSelect<true>;
    'program-detail-page': ProgramDetailPageSelect<false> | ProgramDetailPageSelect<true>;
    'initiative-detail-page': InitiativeDetailPageSelect<false> | InitiativeDetailPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'publications-page': PublicationsPageSelect<false> | PublicationsPageSelect<true>;
    'news-page': NewsPageSelect<false> | NewsPageSelect<true>;
    'stories-page': StoriesPageSelect<false> | StoriesPageSelect<true>;
    'story-detail-page': StoryDetailPageSelect<false> | StoryDetailPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'impact-page': ImpactPageSelect<false> | ImpactPageSelect<true>;
    'research-page': ResearchPageSelect<false> | ResearchPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'news-event-detail-page': NewsEventDetailPageSelect<false> | NewsEventDetailPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * PDF and document uploads (publications, policy briefs, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  /**
   * e.g. PA1, PA2 — used as a stable identifier on the frontend
   */
  code: string;
  title: string;
  /**
   * URL slug. Auto-filled from title; edit to customize.
   */
  slug: string;
  description: string;
  /**
   * Short description for the "What We Do" boxes on the About page (2–3 sentences).
   */
  shortDescription?: string | null;
  /**
   * Theme color for this program area (used for cards, icons, and accents across the site).
   */
  color: string;
  /**
   * Hero image for the program detail page
   */
  heroImage?: (number | null) | Media;
  /**
   * Body content for the program detail page
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * "How we work on this pillar" section
   */
  methodologySection?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sdgs?:
    | {
        goal: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Field projects under this program. Initiatives with "showInProjectsTab" are surfaced in the site-wide Action Hub Projects tab.
   */
  initiatives?:
    | {
        title: string;
        /**
         * URL slug. Auto-filled from title; edit to customize.
         */
        slug: string;
        description: string;
        /**
         * e.g. "Turkana, Kenya"
         */
        location?: string | null;
        status?: ('Planning' | 'Active' | 'Scaling' | 'Field Testing' | 'Completed') | null;
        /**
         * Headline metric, e.g. "12 villages, 4.5M L/yr"
         */
        stat?: string | null;
        /**
         * Icon shown on the initiative card.
         */
        icon?:
          | (
              | 'Layers'
              | 'Rocket'
              | 'Info'
              | 'BarChart3'
              | 'MessageSquareQuote'
              | 'BookOpen'
              | 'Users'
              | 'Heart'
              | 'Globe'
              | 'Target'
              | 'Zap'
              | 'Sprout'
              | 'Droplets'
              | 'ShieldAlert'
              | 'Tractor'
              | 'Check'
              | 'FileText'
              | 'Calendar'
              | 'MapPin'
              | 'ExternalLink'
              | 'Quote'
            )
          | null;
        heroImage?: (number | null) | Media;
        /**
         * Body content for the initiative detail page
         */
        longDescription?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * If on, this initiative appears in the site-wide Action Hub Projects tab.
         */
        showInProjectsTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Key activities shown in the program detail panel on the Programs page.
   */
  keyActivities?:
    | {
        activity: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-events".
 */
export interface NewsEvent {
  id: number;
  title: string;
  /**
   * URL slug. Auto-filled from title; edit to customize.
   */
  slug: string;
  date: string;
  author?: string | null;
  summary: string;
  category: 'Publication' | 'Field Report' | 'Workshop' | 'Funding' | 'Policy' | 'News';
  /**
   * Feature on the homepage
   */
  isHighlight?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Controls display order (lower numbers first). Leave empty to sort last.
   */
  order?: number | null;
  /**
   * Controls how this member is grouped and displayed on the site.
   */
  memberType: 'ceo' | 'pa-manager' | 'advisory' | 'staff';
  /**
   * Toggle whether this team member appears on the site.
   */
  show?: boolean | null;
  /**
   * Reporting line — leave empty for root (Director) and advisory members.
   */
  parent?: (number | null) | Team;
  bio?: string | null;
  /**
   * e.g. "Nairobi, Kenya" — shown for advisory board / collaborating experts.
   */
  location?: string | null;
  /**
   * Optional "Know more" link shown on the network/collaborators page (e.g. a place, university, or profile).
   */
  link?: {
    linkLabel?: string | null;
    /**
     * Full URL, e.g. https://...
     */
    linkUrl?: string | null;
  };
  expertise?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  avatar?: (number | null) | Media;
  /**
   * Program areas this team member is associated with.
   */
  programAreas?: (number | Program)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-volunteers".
 */
export interface FeaturedVolunteer {
  id: number;
  name: string;
  role: string;
  location: string;
  /**
   * Display string, e.g. "March 2022"
   */
  since: string;
  quote: string;
  /**
   * Program area code or name
   */
  program: string;
  /**
   * Fallback avatar text, 1–3 chars
   */
  initials: string;
  /**
   * Tailwind gradient class for avatar background
   */
  gradient: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * URL slug. Auto-filled from title; edit to customize.
   */
  slug: string;
  excerpt: string;
  location: string;
  program: string;
  /**
   * e.g. "5 min read"
   */
  readTime: string;
  date: string;
  /**
   * Shown on the story detail page
   */
  author?: string | null;
  isFeatured?: boolean | null;
  category: string;
  /**
   * Tailwind gradient stops for the placeholder card header, e.g. "from-emerald-600 to-leaf-500".
   */
  gradient?: string | null;
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  category: 'Field Work' | 'Community' | 'Research' | 'Events' | 'Partners';
  location: string;
  year: number;
  image: number | Media;
  caption?: string | null;
  aspectRatio?: ('4/3' | 'square' | '16/10' | '3/4') | null;
  /**
   * Controls how many columns/rows this item spans in the masonry grid.
   */
  gridSize?: ('1x1' | '2x1' | '1x2') | null;
  /**
   * Tailwind gradient stops shown as a placeholder while the image loads.
   */
  gradient?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-metrics".
 */
export interface ImpactMetric {
  id: number;
  value: number;
  /**
   * e.g. "+", "%", "K"
   */
  suffix?: string | null;
  label: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-testimonials".
 */
export interface HomepageTestimonial {
  id: number;
  author: string;
  role: string;
  organization?: string | null;
  quote: string;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * The 4 counter tiles shown on the Volunteer page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-stats".
 */
export interface VolunteerStat {
  id: number;
  /**
   * Display string, e.g. "120+"
   */
  value: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the /contact form — admin read-only
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  organization?: string | null;
  interestArea: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Research papers, policy briefs, annual reports, and workshop outputs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  /**
   * URL slug. Auto-filled from title; edit to customize.
   */
  slug: string;
  /**
   * External publications redirect to the provided URL.
   */
  publicationType: 'internal' | 'external';
  /**
   * Full URL to the publication on ResearchGate or another platform.
   */
  externalUrl?: string | null;
  author?: string | null;
  category?: ('Annual Report' | 'Policy Brief' | 'Research Paper' | 'Workshop' | 'Methodology') | null;
  publishedDate?: string | null;
  summary?: string | null;
  abstract?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * PDF upload — required for public download.
   */
  pdf?: (number | null) | Document;
  /**
   * Optional cover image for listings.
   */
  featuredImage?: (number | null) | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Collaborating universities, research institutes, and NGOs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Short identifier, e.g. "IITA", "ZALF", "CIRAD".
   */
  abbreviation?: string | null;
  type: 'University' | 'Research Institute' | 'NGO' | 'Funding Agency';
  continent: 'Europe' | 'Africa' | 'Global';
  country: string;
  /**
   * Toggle whether this partner/collaborator appears on the network page.
   */
  show?: boolean | null;
  website?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Methodologies and tools featured at the top of the Research & Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-tools".
 */
export interface ResearchTool {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Controls display order (lower numbers first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'news-events';
        value: number | NewsEvent;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'featured-volunteers';
        value: number | FeaturedVolunteer;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'impact-metrics';
        value: number | ImpactMetric;
      } | null)
    | ({
        relationTo: 'homepage-testimonials';
        value: number | HomepageTestimonial;
      } | null)
    | ({
        relationTo: 'volunteer-stats';
        value: number | VolunteerStat;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'research-tools';
        value: number | ResearchTool;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  color?: T;
  heroImage?: T;
  longDescription?: T;
  methodologySection?: T;
  sdgs?:
    | T
    | {
        goal?: T;
        id?: T;
      };
  initiatives?:
    | T
    | {
        title?: T;
        slug?: T;
        description?: T;
        location?: T;
        status?: T;
        stat?: T;
        icon?: T;
        heroImage?: T;
        longDescription?: T;
        showInProjectsTab?: T;
        id?: T;
      };
  keyActivities?:
    | T
    | {
        activity?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-events_select".
 */
export interface NewsEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  author?: T;
  summary?: T;
  category?: T;
  isHighlight?: T;
  content?: T;
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  order?: T;
  memberType?: T;
  show?: T;
  parent?: T;
  bio?: T;
  location?: T;
  link?:
    | T
    | {
        linkLabel?: T;
        linkUrl?: T;
      };
  expertise?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  avatar?: T;
  programAreas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-volunteers_select".
 */
export interface FeaturedVolunteersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  location?: T;
  since?: T;
  quote?: T;
  program?: T;
  initials?: T;
  gradient?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  location?: T;
  program?: T;
  readTime?: T;
  date?: T;
  author?: T;
  isFeatured?: T;
  category?: T;
  gradient?: T;
  image?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  location?: T;
  year?: T;
  image?: T;
  caption?: T;
  aspectRatio?: T;
  gridSize?: T;
  gradient?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-metrics_select".
 */
export interface ImpactMetricsSelect<T extends boolean = true> {
  value?: T;
  suffix?: T;
  label?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-testimonials_select".
 */
export interface HomepageTestimonialsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  organization?: T;
  quote?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-stats_select".
 */
export interface VolunteerStatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  organization?: T;
  interestArea?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publicationType?: T;
  externalUrl?: T;
  author?: T;
  category?: T;
  publishedDate?: T;
  summary?: T;
  abstract?: T;
  pdf?: T;
  featuredImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  type?: T;
  continent?: T;
  country?: T;
  show?: T;
  website?: T;
  logo?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-tools_select".
 */
export interface ResearchToolsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, navigation, footer, social, and SEO defaults applied site-wide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    name: string;
    /**
     * Single-letter logomark shown in the hex-mask header tile.
     */
    logoLetter?: string | null;
    /**
     * Optional logo image. Replaces the letter logomark when set.
     */
    logoImage?: (number | null) | Media;
    tagline?: string | null;
  };
  navigation?: {
    primaryLinks?:
      | {
          label: string;
          path: string;
          children?:
            | {
                label: string;
                path: string;
                description?: string | null;
                /**
                 * Lucide icon name. Frontend resolves to the corresponding lucide-vue-next component.
                 */
                icon?:
                  | (
                      | 'Layers'
                      | 'Rocket'
                      | 'Info'
                      | 'BarChart3'
                      | 'MessageSquareQuote'
                      | 'BookOpen'
                      | 'Users'
                      | 'Heart'
                      | 'Globe'
                      | 'Target'
                      | 'Zap'
                      | 'Sprout'
                      | 'Droplets'
                      | 'ShieldAlert'
                      | 'Tractor'
                      | 'Check'
                      | 'FileText'
                      | 'Calendar'
                      | 'MapPin'
                      | 'ExternalLink'
                      | 'Quote'
                    )
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    ctaButton?: {
      label?: string | null;
      path?: string | null;
    };
  };
  footer?: {
    quickLinks?:
      | {
          label: string;
          path: string;
          id?: string | null;
        }[]
      | null;
    contactPhone?: string | null;
    contactEmail?: string | null;
    contactAddress?: string | null;
    /**
     * Use {year} to auto-insert the current year.
     */
    copyrightText?: string | null;
  };
  social?:
    | {
        platform: 'twitter' | 'linkedin' | 'youtube' | 'instagram' | 'facebook';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Countries where RuralNexus has active field operations. Used to power the interactive map on the Our Network page.
   */
  interventionCountries?:
    | {
        name: string;
        /**
         * ISO 3166-1 alpha-2 code, e.g. "CM" for Cameroon.
         */
        isoCode: string;
        /**
         * Brief note on active programs in this country (shown in map tooltip).
         */
        programs?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    eyebrowTags?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    headlineLine1?: string | null;
    /**
     * Styled italic/gradient span on the frontend.
     */
    headlineEmphasis?: string | null;
    headlineLine2?: string | null;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      path?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      path?: string | null;
    };
  };
  whoWeAre?: {
    eyebrow?: string | null;
    headingLine1?: string | null;
    headingLine2Prefix?: string | null;
    headingLine2Emphasis?: string | null;
    headingLine2Suffix?: string | null;
    body?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
    image?: (number | null) | Media;
    floatingBadge?: {
      /**
       * Lucide icon name. Frontend resolves to the corresponding lucide-vue-next component.
       */
      icon?:
        | (
            | 'Layers'
            | 'Rocket'
            | 'Info'
            | 'BarChart3'
            | 'MessageSquareQuote'
            | 'BookOpen'
            | 'Users'
            | 'Heart'
            | 'Globe'
            | 'Target'
            | 'Zap'
            | 'Sprout'
            | 'Droplets'
            | 'ShieldAlert'
            | 'Tractor'
            | 'Check'
            | 'FileText'
            | 'Calendar'
            | 'MapPin'
            | 'ExternalLink'
            | 'Quote'
          )
        | null;
      title?: string | null;
      body?: string | null;
    };
  };
  /**
   * Pulls the first 3 from the HomepageTestimonials collection.
   */
  testimonialsSection?: {
    heading?: string | null;
  };
  /**
   * Sources rows from the News & Events collection.
   */
  newsSection?: {
    heading?: string | null;
    latestEventsCount?: number | null;
    highlightsCount?: number | null;
  };
  missionSdgSection?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
    featuredSdgs?:
      | {
          goal: number;
          id?: string | null;
        }[]
      | null;
  };
  partnersSection?: {
    heading?: string | null;
    partners?:
      | {
          name: string;
          logoImage?: (number | null) | Media;
          style?: ('text' | 'logo') | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    headingEmphasis?: string | null;
    body?: string | null;
    /**
     * Background image for the header section. If empty, a default image is used.
     */
    backgroundImage?: (number | null) | Media;
  };
  missionVision?: {
    heading?: string | null;
    mission?: string | null;
    vision?: string | null;
  };
  approachSection?: {
    heading?: string | null;
    body?: string | null;
    whatWeDoSubheading?: string | null;
    whatWeDoBullets?:
      | {
          bullet: string;
          id?: string | null;
        }[]
      | null;
    pillars?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  geographySection?: {
    heading?: string | null;
    body?: string | null;
    regions?:
      | {
          name?: string | null;
          /**
           * Comma-separated list
           */
          countries?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  valuesSection?: {
    heading?: string | null;
    values?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-page".
 */
export interface ProgramsPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    headlinePrefix?: string | null;
    headlineEmphasis?: string | null;
    body?: string | null;
    headerBadges?:
      | {
          /**
           * Lucide icon name. Frontend resolves to the corresponding lucide-vue-next component.
           */
          icon?:
            | (
                | 'Layers'
                | 'Rocket'
                | 'Info'
                | 'BarChart3'
                | 'MessageSquareQuote'
                | 'BookOpen'
                | 'Users'
                | 'Heart'
                | 'Globe'
                | 'Target'
                | 'Zap'
                | 'Sprout'
                | 'Droplets'
                | 'ShieldAlert'
                | 'Tractor'
                | 'Check'
                | 'FileText'
                | 'Calendar'
                | 'MapPin'
                | 'ExternalLink'
                | 'Quote'
              )
            | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    heading?: string | null;
    body?: string | null;
    primaryCta?: {
      label?: string | null;
      path?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      path?: string | null;
    };
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Applied to every /programs/:slug page. Program-specific content comes from the Programs collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-detail-page".
 */
export interface ProgramDetailPage {
  id: number;
  initiativesHeading?: string | null;
  ctaHeading?: string | null;
  ctaPath?: string | null;
  backLinkLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Applied to every /programs/:programSlug/initiatives/:initiativeSlug page. Initiative content comes from the Programs.initiatives[] array.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiative-detail-page".
 */
export interface InitiativeDetailPage {
  id: number;
  relatedHeading?: string | null;
  ctaHeading?: string | null;
  ctaPath?: string | null;
  backLinkLabel?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the /projects page header and CTA. Project cards are sourced from Programs → Initiatives where showcase=true.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  ctaSection?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the /publications listing page header and CTA. Publication cards are sourced from the Publications collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications-page".
 */
export interface PublicationsPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  ctaSection?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the /news listing page header and CTA. News cards are sourced from the News & Events collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page".
 */
export interface NewsPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  ctaSection?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories-page".
 */
export interface StoriesPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    headlinePrefix?: string | null;
    headlineEmphasis?: string | null;
    body?: string | null;
  };
  /**
   * Pulls the first Story with isFeatured=true.
   */
  featuredSection?: {
    overrideCategoryLabel?: string | null;
  };
  gridSection?: {
    headingPrefix?: string | null;
    headingEmphasis?: string | null;
    body?: string | null;
    filterButtonLabel?: string | null;
    loadMoreLabel?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Applied to every /stories/:slug page. Per-story content comes from the Stories collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-detail-page".
 */
export interface StoryDetailPage {
  id: number;
  backLinkLabel?: string | null;
  relatedHeading?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
  };
  filters?: {
    allLabel?: string | null;
    /**
     * Controls the filter bar order on the frontend.
     */
    categoryOrder?:
      | {
          value: 'Field Work' | 'Community' | 'Research' | 'Events' | 'Partners';
          id?: string | null;
        }[]
      | null;
  };
  loadMoreLabel?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Metric cards are sourced from the ImpactMetrics collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page".
 */
export interface ImpactPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    headlinePrefix?: string | null;
    headlineEmphasis?: string | null;
    body?: string | null;
  };
  assessmentSection?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
    badges?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Publications grid is sourced from the Publications collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-page".
 */
export interface ResearchPage {
  id: number;
  header?: {
    eyebrow?: string | null;
    headlinePrefix?: string | null;
    headlineEmphasis?: string | null;
    body?: string | null;
  };
  filtersSection?: {
    searchPlaceholder?: string | null;
    categories?:
      | {
          label: string;
          /**
           * Lucide icon name. Frontend resolves to the corresponding lucide-vue-next component.
           */
          icon?:
            | (
                | 'Layers'
                | 'Rocket'
                | 'Info'
                | 'BarChart3'
                | 'MessageSquareQuote'
                | 'BookOpen'
                | 'Users'
                | 'Heart'
                | 'Globe'
                | 'Target'
                | 'Zap'
                | 'Sprout'
                | 'Droplets'
                | 'ShieldAlert'
                | 'Tractor'
                | 'Check'
                | 'FileText'
                | 'Calendar'
                | 'MapPin'
                | 'ExternalLink'
                | 'Quote'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    emptyStateHeading?: string | null;
    emptyStateBody?: string | null;
    clearFiltersLabel?: string | null;
  };
  submitCtaSection?: {
    badge?: string | null;
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaPath?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  header?: {
    heading?: string | null;
    body?: string | null;
  };
  formSection?: {
    heading?: string | null;
    body?: string | null;
    interestAreas?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    submitLabel?: string | null;
    successMessage?: string | null;
  };
  hqSection?: {
    eyebrow?: string | null;
    orgName?: string | null;
    address?: string | null;
    directionsUrl?: string | null;
  };
  directContacts?: {
    eyebrow?: string | null;
    contacts?:
      | {
          label: string;
          email: string;
          /**
           * Lucide icon name. Frontend resolves to the corresponding lucide-vue-next component.
           */
          icon?:
            | (
                | 'Layers'
                | 'Rocket'
                | 'Info'
                | 'BarChart3'
                | 'MessageSquareQuote'
                | 'BookOpen'
                | 'Users'
                | 'Heart'
                | 'Globe'
                | 'Target'
                | 'Zap'
                | 'Sprout'
                | 'Droplets'
                | 'ShieldAlert'
                | 'Tractor'
                | 'Check'
                | 'FileText'
                | 'Calendar'
                | 'MapPin'
                | 'ExternalLink'
                | 'Quote'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Applied to every /news/:slug page. Per-article content comes from the NewsEvents collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-event-detail-page".
 */
export interface NewsEventDetailPage {
  id: number;
  backLinkLabel?: string | null;
  /**
   * Use {category} to inject the current article category.
   */
  relatedHeading?: string | null;
  notFoundHeading?: string | null;
  notFoundBody?: string | null;
  notFoundCtaLabel?: string | null;
  notFoundCtaPath?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        logoLetter?: T;
        logoImage?: T;
        tagline?: T;
      };
  navigation?:
    | T
    | {
        primaryLinks?:
          | T
          | {
              label?: T;
              path?: T;
              children?:
                | T
                | {
                    label?: T;
                    path?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
            };
        ctaButton?:
          | T
          | {
              label?: T;
              path?: T;
            };
      };
  footer?:
    | T
    | {
        quickLinks?:
          | T
          | {
              label?: T;
              path?: T;
              id?: T;
            };
        contactPhone?: T;
        contactEmail?: T;
        contactAddress?: T;
        copyrightText?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  interventionCountries?:
    | T
    | {
        name?: T;
        isoCode?: T;
        programs?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrowTags?:
          | T
          | {
              value?: T;
              id?: T;
            };
        headlineLine1?: T;
        headlineEmphasis?: T;
        headlineLine2?: T;
        subtitle?: T;
        backgroundImage?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              path?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              path?: T;
            };
      };
  whoWeAre?:
    | T
    | {
        eyebrow?: T;
        headingLine1?: T;
        headingLine2Prefix?: T;
        headingLine2Emphasis?: T;
        headingLine2Suffix?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaPath?: T;
        image?: T;
        floatingBadge?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
            };
      };
  testimonialsSection?:
    | T
    | {
        heading?: T;
      };
  newsSection?:
    | T
    | {
        heading?: T;
        latestEventsCount?: T;
        highlightsCount?: T;
      };
  missionSdgSection?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
        ctaPath?: T;
        featuredSdgs?:
          | T
          | {
              goal?: T;
              id?: T;
            };
      };
  partnersSection?:
    | T
    | {
        heading?: T;
        partners?:
          | T
          | {
              name?: T;
              logoImage?: T;
              style?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingEmphasis?: T;
        body?: T;
        backgroundImage?: T;
      };
  missionVision?:
    | T
    | {
        heading?: T;
        mission?: T;
        vision?: T;
      };
  approachSection?:
    | T
    | {
        heading?: T;
        body?: T;
        whatWeDoSubheading?: T;
        whatWeDoBullets?:
          | T
          | {
              bullet?: T;
              id?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  geographySection?:
    | T
    | {
        heading?: T;
        body?: T;
        regions?:
          | T
          | {
              name?: T;
              countries?: T;
              id?: T;
            };
      };
  valuesSection?:
    | T
    | {
        heading?: T;
        values?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs-page_select".
 */
export interface ProgramsPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        headlinePrefix?: T;
        headlineEmphasis?: T;
        body?: T;
        headerBadges?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        body?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              path?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              path?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-detail-page_select".
 */
export interface ProgramDetailPageSelect<T extends boolean = true> {
  initiativesHeading?: T;
  ctaHeading?: T;
  ctaPath?: T;
  backLinkLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiative-detail-page_select".
 */
export interface InitiativeDetailPageSelect<T extends boolean = true> {
  relatedHeading?: T;
  ctaHeading?: T;
  ctaPath?: T;
  backLinkLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
        ctaPath?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications-page_select".
 */
export interface PublicationsPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
        ctaPath?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page_select".
 */
export interface NewsPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
        ctaPath?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories-page_select".
 */
export interface StoriesPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        headlinePrefix?: T;
        headlineEmphasis?: T;
        body?: T;
      };
  featuredSection?:
    | T
    | {
        overrideCategoryLabel?: T;
      };
  gridSection?:
    | T
    | {
        headingPrefix?: T;
        headingEmphasis?: T;
        body?: T;
        filterButtonLabel?: T;
        loadMoreLabel?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-detail-page_select".
 */
export interface StoryDetailPageSelect<T extends boolean = true> {
  backLinkLabel?: T;
  relatedHeading?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  filters?:
    | T
    | {
        allLabel?: T;
        categoryOrder?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  loadMoreLabel?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page_select".
 */
export interface ImpactPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        headlinePrefix?: T;
        headlineEmphasis?: T;
        body?: T;
      };
  assessmentSection?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
        ctaPath?: T;
        badges?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-page_select".
 */
export interface ResearchPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        headlinePrefix?: T;
        headlineEmphasis?: T;
        body?: T;
      };
  filtersSection?:
    | T
    | {
        searchPlaceholder?: T;
        categories?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        emptyStateHeading?: T;
        emptyStateBody?: T;
        clearFiltersLabel?: T;
      };
  submitCtaSection?:
    | T
    | {
        badge?: T;
        heading?: T;
        body?: T;
        ctaLabel?: T;
        ctaPath?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  formSection?:
    | T
    | {
        heading?: T;
        body?: T;
        interestAreas?:
          | T
          | {
              value?: T;
              id?: T;
            };
        submitLabel?: T;
        successMessage?: T;
      };
  hqSection?:
    | T
    | {
        eyebrow?: T;
        orgName?: T;
        address?: T;
        directionsUrl?: T;
      };
  directContacts?:
    | T
    | {
        eyebrow?: T;
        contacts?:
          | T
          | {
              label?: T;
              email?: T;
              icon?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-event-detail-page_select".
 */
export interface NewsEventDetailPageSelect<T extends boolean = true> {
  backLinkLabel?: T;
  relatedHeading?: T;
  notFoundHeading?: T;
  notFoundBody?: T;
  notFoundCtaLabel?: T;
  notFoundCtaPath?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}